root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ."
bin = "tmp/main.exe"
full_bin = "./tmp/main.exe"

include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true

[screen]
clear_on_rebuild = true
